### ISSUE TITLE
brainstorm dataset and statistic analysis question

### ISSUE THREAD

**Issue by KangboLu** [UBC-MDS/DSCI_522_Group_34#1]
**Let's discuss what datasets and statistic questions you have in mind for our project:**
After our discussion, we will write the proposal together in the README.md file.

> the proposal should be written in the README.md file in the root of your public GitHub.com repo.

The requirements and data source suggestions from the milestone 1 specification: [click here](https://github.ubc.ca/MDS-2020-21/DSCI_522_dsci-workflows_students/blob/master/release/milestone1/milestone1.md#2-project-proposal)

You can copy the text below for a discussion template if you want:
- Dataset:
- Public URL(non-Kaggle for easier download script writing):
- 1 possible Statistic question to answer:

**Comment by roycezhou** [comment]
FYI [dataset url](https://archive.ics.uci.edu/ml/index.php)

**Comment by KangboLu** [comment]
- **Dataset**:[ Vancouver Graffiti Data by Location](https://opendata.vancouver.ca/explore/dataset/graffiti/information/?sort=count&dataChart=eyJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJib3hwbG90IiwiZnVuYyI6IkNPVU5UIiwieUF4aXMiOiJjb3VudCIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiMwMjc5QjEiLCJjaGFydHMiOlt7ImZ1bmMiOiJNSU4iLCJ5QXhpcyI6ImNvdW50In0seyJmdW5jIjoiUVVBTlRJTEVTIiwieUF4aXMiOiJjb3VudCIsInN1YnNldHMiOjI1fSx7ImZ1bmMiOiJRVUFOVElMRVMiLCJ5QXhpcyI6ImNvdW50Iiwic3Vic2V0cyI6NTB9LHsiZnVuYyI6IlFVQU5USUxFUyIsInlBeGlzIjoiY291bnQiLCJzdWJzZXRzIjo3NX0seyJmdW5jIjoiTUFYIiwieUF4aXMiOiJjb3VudCJ9XX1dLCJ4QXhpcyI6Imdlb19sb2NhbF9hcmVhIiwibWF4cG9pbnRzIjo1MCwic29ydCI6IiIsImNvbmZpZyI6eyJkYXRhc2V0IjoiZ3JhZmZpdGkiLCJvcHRpb25zIjp7InNvcnQiOiJjb3VudCJ9fX1dLCJ0aW1lc2NhbGUiOiIiLCJkaXNwbGF5TGVnZW5kIjp0cnVlLCJhbGlnbk1vbnRoIjp0cnVlfQ%3D%3D&location=14,49.28084,-123.09806)
- **Public URL**: https://opendata.vancouver.ca/explore/dataset/graffiti/download/?format=csv&timezone=Asia/Shanghai&lang=en&use_labels_for_header=true&csv_separator=%3B
- **1 Statistic question**: 
Is the number of graffiti per location of the Vancouver's downtown area differs from the number of graffiti per location of the Vancouver Strathcona area?

We can do EDA and conduct Hypothesis testing with a suitable test flavor: 
Does the median/mean number of graffiti per location of Vancouver's downtown area differ from the median/mean number of graffiti per location of Vancouver's Strathcona area?

We can use the "count" and "geo local area" columns to do permutation for hypothesis testing.

**Comment by shoebillm** [comment]
**Dataset:** [DASH - Global School-based Student Health Survey ](https://chronicdata.cdc.gov/Youth-Risk-Behaviors/DASH-Global-School-based-Student-Health-Survey-GSH/pxpe-pgrg)
**Public URL(non-Kaggle for easier download script writing):** https://data.cdc.gov/api/views/pxpe-pgrg/rows.csv?accessType=DOWNLOAD
**1 possible Statistic question to answer**: Overall in all regions from 2003 to 2015, do female and male students have different percentages of most of the time or always felt lonely?

1. Need to filter data to keep only the "most of the time or always felt lonely" from the "greater risk question" column, and select to keep the relevant columns only (region, gender, greater risk questions, greater risk data value, sample size, etc. Remove the gender = total data entries.

2. Conduct hypothesis testing by permutation or CLT to examine whether the sampling mean greater risk value in percentage is independent of gender or not.
