### ISSUE TITLE
Add error handling and usage for download_data.R script

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/DSCI_522_Group_34#24]
I suggest you add error handling to detect errors in user inputs when calling the script. I also suggest you provide in the project README file how to call this script and what arguments to provide.

**Comment by KangboLu** [comment]
Okay, that's more for [milestone 2's requirement](https://github.ubc.ca/MDS-2020-21/DSCI_522_dsci-workflows_students/blob/master/release/milestone2/milestone2.md) to put the how-to part in README.md.
If you read the requirement for [milestone one](https://github.ubc.ca/MDS-2020-21/DSCI_522_dsci-workflows_students/blob/master/release/milestone1/milestone1.md), there is no requirement for the usage section, although the example repo's milestone 1 release has the usage section. If that's what's required, we will have to copy what are exactly covered in the example repo to get full marks.
