### ISSUE TITLE
Plots and tables code in the EDA file

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/DSCI_522_Group_34#25]
Always provide the code for plots and tables in the EDA file

**Comment by KangboLu** [comment]
@hsmohammed It's not required for showing the code in the rendered md file for R Markdown. We followed Tiffany's example render see here. She didn't suggest to have to include code in the render. See her rendered md file here:
https://github.com/ttimbers/breast_cancer_predictor/blob/master/src/breast_cancer_eda.md

> 4. Exploratory data analysis in a literate code document
Choose a format to submit your exploratory data analysis, either an Rmd file or a Jupyter notebook. 
This should serve as a pre-cursor to the scripts you will eventually create. 
Feel free to experiment with different analyses and visualizations in this document. 
Data scientists often use a sandbox to play around in, before final scripts are created for automation. 
Similarly, it is valuable to try out a few different plots before finally settling on one or two for the final report. 
Note - the EDA should be done in a literate code document (e.g., .Rmd or .ipynb file). If you choose .Rmd, also please include a rendered document that we can easily read on GitHub (e.g., .md or .pdf). These documents should live in a subdirectory, such as src or make one called eda. You should point to this file in the README of your public GitHub.com repo.

Which EDA file are you referring? R script, R markdown, rendered GitHub markdown? Please be more specific about which milestone are you referring to also?

**Comment by ttimbers** [comment]
We talked about this, and yes, it is OK to hide the code chunks for the EDA (as long as the source file is in the repo as well - which in this case it is). Apologies for the miscommunication.
