### ISSUE TITLE
data folder

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/DSCI_522_Group_34#36]
I suggest you put the data folder in the .gitignore. There is no need to upload the data files to github.

**Comment by KangboLu** [comment]
@hsmohammed 
Having a data folder is considered a good file structure though and our data is small with a size of only 700kb. 
Can we upload although it's not required? There is no specification saying we can't do it. Many groups are also including the data folder with data. We don't see there is "no need" to upload the data files to Github.

**Comment by shoebillm** [comment]
Hi @hsmohammed,
According to the example provided by Tiff, we thought we needed to provide the specific file in the folders to show that our commands actually worked for storing the data? Could you explain more on how to prove we successfully downloaded it if not showing the data downloaded/file structure in our repo? Thank you!
<img width="1145" alt="Screen Shot 2020-11-28 at 2 46 37 PM" src="https://user-images.githubusercontent.com/48242437/100495665-ac3e2800-3188-11eb-94de-156abb6e5583.png">
<img width="896" alt="Screen Shot 2020-11-28 at 2 51 52 PM" src="https://user-images.githubusercontent.com/48242437/100495729-60d84980-3189-11eb-9499-8a0eb01de6c7.png">
