### ISSUE TITLE
Assignment4 Feedback From Neel 

### ISSUE THREAD

**Issue by nphaterp** [UBC-MDS/DSCI_522_Group_34#61]
Hey guys. I enjoyed reviewing your project. Here are my points of feedback, take them with a grain of salt because I am no expert. 

- Documentation:
The project repo structure is clear and well-organized.
The report files are well-written and the rendered format is also good and easy to follow.

- I notice that the link provided in the README  (where you say "from the Vancouver Open Data Portal and it can be found [here]" does not actually bring you to the data. Note that you do provide the correct link in the actual report which is great. 

- Code:
All codes work well and are readable.
The makefiles are constructed properly.

Analysis and reasoning:

- Figure 2 in the report. I would suggest that the figure itself is not adding too much to your report. Seems like stating your test statistic and p-value would be sufficient enough to convey the information. However, if you do decide to keep the plot in, I would suggest making a text annotation explaining what the red line is (eg. 'test statistic') because it may not be clear to someone who is not in our class. Furthermore, you could add the borders of the 2.5th and 97.5th percentiles to indicate the confidence interval of where your test-statistic needed to fall under to be considered not significant.

- One final small note; I would suggest that everyone in your group try to give the report another quick read to try to edit some of the grammatical errors that are sprinkled within (sorry for being picky about that).

Overall I think you guys are doing a great job. Feel free to reach out if you want any clarifications about anything I have suggested.

**Comment by KangboLu** [comment]
The first link is for the open data portal URL. The second link is the actual file. 
![image](https://user-images.githubusercontent.com/17485959/101737243-9113d680-3aff-11eb-8f06-1cecc7f64040.png)
Thanks for the feedback. We will make adjustments to our report.
