### ISSUE TITLE
Milestone 3 Peer Review from William

### ISSUE THREAD

**Issue by williamxu7** [UBC-MDS/DSCI_522_Group_34#62]
Hello team 34, great job on the project overall, I enjoyed reading your report. 

Your project documentation is clear and easy to follow for a wide range of audiences. The code looks good and readable. The overall analysis looks thorough. The violin plot is cool and it tells a good story. Your scripts have enough comments and well-organized.

It's interesting to see that the model failed to reject the null hypothesis that "the median number of graffiti per recorded location of Vancouver Downtown area is the same as the median number of graffiti per recorded location of Vancouver Strathcona area".

Some areas can be improved potentially:
- Laytex for significance level alpha in the final report can be fixed. Some minor formatting and grammatical refinement in the final report. 
- Figure 2 in the report, I finding it not very meaningful for the analysis purpose. Maybe it can be removed, or replaced with a different plot, or add a little bit more context to tell a story.

**Comment by shoebillm** [comment]
@williamxu7 Thanks for taking time reviewing our project and providing feedback! We will make changes accordingly.
